[package]
name = "imessage_parser"
version = "0.1.0"
edition = "2021"

[lib]
name = "imessage_parser"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.29"
imessage-database = { path = "vendor/imessage-exporter/imessage-database" }